### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by jmdobry** [neumino/rethinkdbdash#46] opened 2014-10-03 16:11 UTC
The official driver runs in the browser. Is there any way to get rethinkdbdash to run in the browser, perhaps with Browserify?

Currently I get `'Error: Cannot find module '/node_modules/rethinkdbdash/lib/helper.js'` when requiring rethinkdbdash and building with Browserify.

**Comment by ilsken** [comment] 2015-04-16 17:56
Perhaps a library akin to [minimongo](https://github.com/mWater/minimongo) would be more appropriate for browsers. I'd even be happy with the client side version allowing you specify a `query` handler which would let you handle queries however you want

```js
// actual api should be something that looks more natural than this
r.setQueryHandler(function (query) {
   return sendQueryToBackEndAndReturnPromise(query); // query being a JSON serialized version of any ReQL query after `.run` is called
});
```

Server side:
```js
app.post('/api/', function (req, res) {
    var query = r.reqlFromJSON(req.query);
   query.run(); // you would ideally do some security checks on req.query before you unserialize and run it
});
```

**Comment by neumino** [comment] 2015-04-17 04:01
This issue is about a browser directly connecting to RethinkDB via HTTP instead of using simple TCP connections.

If you want a mini-mongo, you can hook https://github.com/neumino/reqlite with rethinkdbdash. Reqlite implements most of the term baring the geo-spatial ones and changefeeds I think.

**Comment by ilsken** [comment] 2015-04-17 15:43
Ah sorry I misread the issue! If I'm understanding correctly rethink only supports HTTP officially via the endpoint for the admin interface, correct? If that's the case I'd say still have the driver generate whatever queries it wants to execute and let the user define a function that sends the actual request. Opens the door for other transports (web sockets, backend that does some additional security filtering or proxies the request safely to the backend ajax endpoint without exposing the web interface to the world, etc). 


I know that's a tall order and really would require making the "transport" a pluggable part of the driver but I think it could lead to some interesting things. Transport being a single function that takes a query and returns a promise for the result. Would even make it easy to add support for weird environments like Chromecast via the message bus API or something

**Comment by neumino** [comment] 2015-08-16 16:41
Closing as duplicate of #11

**Closed by neumino** 2015-08-16 16:41 UTC
