### ISSUE TITLE
Error: No more rows in the cursor

### ISSUE THREAD

**Issue by medokin** [neumino/rethinkdbdash#169] opened 2015-10-27 23:48 UTC
```json
"rethinkdbdash": "^2.1.12"
```

```js
var result = r.table('mailboxes').run(); // Error, see below

var result = r.table('mailboxes').orderBy('id').run(); //works fine
```

```
Unhandled rejection ReqlDriverError: No more rows in the Cursor.
    at C:\dev\node\usermail\web-api\node_modules\rethinkdbdash\lib\cursor.js:57:
14
    at Promise._execute (C:\dev\node\usermail\web-api\node_modules\rethinkdbdash
\node_modules\bluebird\js\release\debuggability.js:140:9)
    at Promise._resolveFromExecutor (C:\dev\node\usermail\web-api\node_modules\r
ethinkdbdash\node_modules\bluebird\js\release\promise.js:457:18)
    at new Promise (C:\dev\node\usermail\web-api\node_modules\rethinkdbdash\node
_modules\bluebird\js\release\promise.js:76:14)
    at Cursor._next (C:\dev\node\usermail\web-api\node_modules\rethinkdbdash\lib
\cursor.js:52:11)
    at resolve (C:\dev\node\usermail\web-api\node_modules\rethinkdbdash\lib\curs
or.js:228:14)
    at tryCatcher (C:\dev\node\usermail\web-api\node_modules\rethinkdbdash\node_
modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\dev\node\usermail\web-api\node_modu
les\rethinkdbdash\node_modules\bluebird\js\release\promise.js:486:31)
    at Promise._settlePromise (C:\dev\node\usermail\web-api\node_modules\rethink
dbdash\node_modules\bluebird\js\release\promise.js:549:18)
    at Promise._settlePromiseCtx (C:\dev\node\usermail\web-api\node_modules\reth
inkdbdash\node_modules\bluebird\js\release\promise.js:586:10)
    at Async._drainQueue (C:\dev\node\usermail\web-api\node_modules\rethinkdbdas
h\node_modules\bluebird\js\release\async.js:130:12)
    at Async._drainQueues (C:\dev\node\usermail\web-api\node_modules\rethinkdbda
sh\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\dev\node\usermail\web-a
pi\node_modules\rethinkdbdash\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by thelinuxlich** [comment] 2015-10-27 23:50
Probably duplicate of #167

**Comment by neumino** [comment] 2015-10-28 00:01
Closing as duplicate.

**Closed by neumino** 2015-10-28 00:01 UTC
