### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by llambda** [neumino/rethinkdbdash#103] opened 2015-06-27 15:20 UTC
Hello, I have just seen the following in my server log:

```
Process exit at 2015-06-27T15:15:18.897Z
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:158:12)
    at Socket.Writable.write (_stream_writable.js:203:5)
    at Socket.write (net.js:615:40)
    at /home/u/app/node_modules/rethinkdbdash/lib/connection.js:81:23
    at Object.tryCatch (/home/u/app/node_modules/rethinkdbdash/lib/helper.js:156:3)
    at Socket.<anonymous> (/home/u/app/node_modules/rethinkdbdash/lib/connection.js:80:12)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1029:10)
worker 3030 died
```

This is on rethinkdbdash 2.0.12, iojs v2.3.1, and rethinkdb 2.0.3 on Linux. Is this a bug?

**Comment by neumino** [comment] 2015-06-27 16:48
Do you know what query triggered this error?
It looks like it's a writable stream. Did you close it and the did you insert something?

**Comment by llambda** [comment] 2015-06-29 16:02
Just a plain delete query. No streams in the query or anything like that. I do use streaming read queries, from other queries if perhaps those got returned to the pool and then used by the delete query.

**Comment by neumino** [comment] 2015-06-29 16:08
Ok never mind, I see what the problem.

A connection was opened and immediately closed. I wrapped some code in a try/catch, but I should have moved the `error` listener before the `connect` listener.

**Comment by neumino** [comment] 2015-06-29 16:08
I'll push a fix tonight.

**Comment by llambda** [comment] 2015-06-29 17:29
Awesome!

**Closed** 2015-06-30 04:44 UTC

**Comment by neumino** [comment] 2015-06-30 04:46
It should be fixed in 2.0.14 -- but I don't have a way to actually reproduce the error. Let me know if it happens again.

**Comment by neumino** [comment] 2015-06-30 05:44
Even wrote a blog post about: http://blog.justonepixel.com/geek/2015/06/29/rethinkdbdash-bug-103/ :p

**Comment by llambda** [comment] 2015-07-08 15:13
Nice work, @neumino . I updated and have not seen the error anymore.
