### ISSUE TITLE
Improve toStream() docs

### ISSUE THREAD

**Issue by pensierinmusica** [neumino/rethinkdbdash#64] opened 2015-02-13 00:30 UTC
Hi,

I think it'd be good to mention in the docs for `toStream()` that a db other than "test" needs to be specified by the user.

Here's what I mean.

**Current version:**

```javascript
var logs = r.table('logs').toStream({transform: true, returnChanges: false});
```

**Suggested edit**

```javascript
var logs = r.db('my_db_name').table('logs').toStream({transform: true, returnChanges: false});
```

I know it might seem superfluous, but I was getting some errors because it's easy to forget (since for most other operations the db is set through connection options instead).

```javascript
var opts = {
  host: 'localhost',
  port: 28015,
  db: 'my_db_name'
}

var conn;

r.connect(opts)
  .then(function (connection) {
    conn = connection;
    return r.tableCreate('test').run(conn)
  })
  .then(function () {
    // some operations...
  });
```

If you like I can generate a PR for this, let me know your thoughts.

Thanks!

**Comment by neumino** [comment] 2015-02-13 06:12
This works fine for me:
```
var r = require('rethinkdbdash')({pool: false});
var assert = require('assert');

var foo = 'dsadasdasdsa';
r.connect({db: foo}).bind({}).then(function(conn) {
    this.conn = conn;
    return r.dbCreate(foo).run(this.conn)
}).then(function(result) {
    assert.equal(result.dbs_created, 1);
    return r.tableCreate(foo).run(this.conn);
}).then(function(result) {
    assert.equal(result.tables_created, 1);
    return r.table(foo).insert({id: "bar", foo: foo}).run(this.conn);
}).then(function(result) {
    assert.equal(result.inserted, 1);
    return r.table(foo).get("bar").run(this.conn);
}).then(function(result) {
    assert.deepEqual(result, {id: "bar", foo: foo});
    this.conn.close()
})
```

It creates the table `dsadasdasdsa.dsadasdasdsa` with a document.

You can also execute the module with the default database
```
var r = require('rethinkdbdash')({db: "default_db"})
```

I dropped the `db` term from the readme because people usually use a unique database, which they can set when they import the module (or open the connection with `r.connect`).

What may happen in your case is that you open a new connection with the good default database, but call `toStream` without connection, so it will use the connection pool, which may not use the good default database (but the one passed when you import the module).

**Comment by pensierinmusica** [comment] 2015-02-14 12:29
Thanks for the clarifications! Two questions:

1) You say "you open a new connection with the good default database, but call toStream without connection". How do you call `toStream` with a connection, could you please give me a brief code example, or add it to the docs?

2) In your previous reply there's `r.connect({db: foo}).bind({})`. What is the `bind` method, and where is the documentation for it? I couldn't find it either on rethinkdbdash, or rethinkdb docs.

**Comment by neumino** [comment] 2015-02-14 15:44
Sorry I realized that I missed to write that in the Readme. I just pushed a fix. The syntax is
```
r.table('data').toStream(connection) // readable stream
r.table('data').toStream(connection, {writable: true})
```

About `bind`, it's a bluebird method:
https://github.com/petkaantonov/bluebird/blob/master/API.md#binddynamic-thisarg---promise
Basically it set the context for the anonymous function in `then`. It lets you keep track of some variable (in this case the connection), so you can properly close it at the end,

**Comment by pensierinmusica** [comment] 2015-02-15 13:24
Ok, thanks! Btw, `toStream` only works properly as writable stream for ~ 100 docs, then it stays stil and doesn't write anymorel. Not sure why... Should I open another issue? Have you ever tested it with a long stream (above 1M docs)? Cheers!

**Closed** 2015-02-15 13:24 UTC

**Comment by neumino** [comment] 2015-02-15 15:53
A few ideas:
- Make sure that you are using the last version (1.16)
- If you are using a Transform stream, make sure you pipe it to something

If it's none of the above, please open an issue with a snippet to reproduce this. I just piped 100k document and it worked fine.
