### ISSUE TITLE
Node v6.6.0 PBKDF2() Out of Memory

### ISSUE THREAD

**Issue by scttcper** [neumino/rethinkdbdash#293] opened 2016-09-16 20:51 UTC
Updated from node v6.5.0 to v6.6.0 and now I'm getting a weird crash. I've narrowed it down to rethinkdbdash 2.3.23 or  the included version of rethinkdb. 

```
$ node -v
v6.6.0
$ npm -v
3.10.7
```

```javascript
$node
> const r = require('rethinkdbdash')();
Creating a pool connected to localhost:28015
undefined
> FATAL ERROR: node::PBKDF2() Out of Memory
 1: node::Abort() [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 3: node::ClearFatalExceptionHandlers(node::Environment*) [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 4: node::crypto::RandomBytesWork(uv_work_s*) [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/scoope7/.nvm/versions/node/v6.6.0/bin/node]
 8: 0x3082330092a7
 9: 0x3082332562bd
[1]    26049 abort      node
```

**Comment by neumino** [comment] 2016-09-17 01:32
How much memory do you have on your machine? You just ran out of memory.
Maybe there's a bug in crypto in 6.6.0

**Comment by scttcper** [comment] 2016-09-17 03:13
My coworker told me about the error and I reproduced the same error after updating to v6.6.0.
osx 10.11.6. Node installed via nvm.

It probably is a v6.6.0 PBKDF2 bug. hmmm.... 😐

**Comment by scttcper** [comment] 2016-09-17 04:22
I've narrowed it down to the following from connection.js which crashes every time. Can close this.

```javascript
var crypto = require('crypto');

var salt = new Buffer('McWpw6FL29zJ6E97Le3hKQ==', 'base64')
crypto.pbkdf2('', salt, 1, 32, "sha256", function(error, saltedPassword) {
  console.log(error)
  console.log(saltedPassword)
})
```

**Comment by niieani** [comment] 2016-09-17 08:53
I think this should be left open until the issue is resolved in Node. Will save time for others trying to figure out what's wrong...

**Comment by neumino** [comment] 2016-09-17 16:27
Let's keep it open such that it's easier for people to find the link to the node's bug.

**Comment by nfantone** [comment] 2016-09-28 01:41
@scttcper I can confirm that with the [recent release](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-09-27-version-670-current-evanlucas) of `6.7.0`, this no longer happens. 

@neumino You may consider closing the issue.

**Closed** 2016-10-07 03:12 UTC
